FROM node:14-alpine AS build
WORKDIR /app
COPY ./package*.json .
RUN npm i
copy . . 
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html/
CMD ["nginx", "-g", "daemon off;"]